function T1 = T1(delta, sigmazzS, omegaI, omegaS, tau)
% calculates T1 time 
T1 = ((delta/4)^2*(1*J(omegaI-omegaS,tau)+3*J(omegaS,tau) + ... 
6*J(omegaI+omegaS,tau))+ ... 
3/4*(sigmazzS*omegaS).^2.*J(omegaS,tau)).^-1;