function T1z = T1z(delta, sigmazzI, sigmazzS, omegaI, omegaS, tau)
% calculates T1 time 
T1z = ((delta/4)^2*(3*J(omegaI,tau) + 3*J(omegaS,tau)) ... 
     + 3/4*(sigmazzS*omegaS).*J(omegaS,tau) ...
     + 3/4*(sigmazzI*omegaI).*J(omegaI,tau)).^-1;