function T2 = T2(delta, sigmazz, omegaI, omegaS, tau)
% calculates T2 time    
    T2 = (delta^2/32*(4*J(0,tau)+1*J(omegaI-omegaS,tau)+3*J(omegaS,tau) + ...
    6*J(omegaI,tau) +6*J(omegaI+omegaS,tau))+ ...
    1/2*(sigmazz*omegaS).^2.*J(0,tau) + ... 
    3/8*(sigmazz*omegaS).^2.*J(omegaS,tau)).^-1;
